# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 082d53bb989cac6a7c8ac6e432da48974de9dea596b7b00ed2bf075d1571edc9c8c652350a87fac071aabf89426e2cd0011d3d4b1145cb503061efd1d6602e2d

test:
  secret_key_base: 1c87bc61959a2d37df6e256f799e996e18ad2afc44618992c41ed0d471e50dced6178dc49a8b69fb6500eaf752d60362264d0ce6a4e4837ed1fb5924dfd62520

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
